name = "MiniQhull"
uuid = "978d7f02-9e05-4691-894f-ae31a51d76ca"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>", "Victor Sande <vsande@cimne.upc.edu>"]
version = "0.3.0"

[deps]
QhullMiniWrapper_jll = "0d2bb0ae-7f19-52c3-b7ac-00785fe1ed84"

[compat]
julia = "1.3"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
